### ISSUE TITLE
Logic xử lý kém

### ISSUE THREAD

**Issue by danbn-100295** [tranphong9mx/flutter_booking_app#2]
Logic xử lý kém
Đơn thuần là ui
Cần cải thiện nhiều

**Comment by tranphong9mx** [comment]
Cám ơn bạn đã nhận xét giúp mình. Nếu có thể chỉ ra cho mình những lỗi sai thì mình cảm kích rất nhiều ạ! Vì trong quá trình học hỏi nên mình thừa nhận những yếu kém! Cám ơn nhiều ạ!
